#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: charts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: charts
    spec:
      volumes:
      - name: charts-nfs-pv
        persistentVolumeClaim:
          claimName: charts-nfs-claim0
      - name: tools-nfs-pv
        persistentVolumeClaim:
          claimName: tools-nfs-claim0
      containers:
      - name: charts
        image: egaraev/charts:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.1"
            memory: 300Mi
        volumeMounts:
        - name: charts-nfs-pv
          mountPath: /var/www/html/images
        - name: tools-nfs-pv
          mountPath: /usr/local/bin/data

