#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: charts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: charts
    spec:
      containers:
      - name: charts
        image: egaraev/charts:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.05"
            memory: 100Mi