apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: crypto
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
#     - type: docker
#       enabled: false
#       containers.ids:
#       - "*"
#       document_type: docker_logs
#       processors:
#         - add_kubernetes_metadata:
#             in_cluster: true
#     - type: stdin
#       enabled: false
