apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-modules
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  system.yml: |-
    - module: system
      syslog:
        enabled: true
        var.paths: ["/var/log/messages*"]
      auth:
        enabled: true
        var.paths: ["/var/log/secure*"]
