apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.registry_file: /usr/share/filebeat/data/filebeat_registry
    filebeat.config:
      inputs:
        # Mounted `filebeat-prospectors` configmap:
        path: /usr/share/filebeat/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: /usr/share/filebeat/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition.not:
                or:
                  - equals:
                      kubernetes.namespace: kube-system
                  - equals:
                      kubernetes.namespace: kube-public 
              config:
                - type: docker
                  document_type: docker_logs
                  containers.ids:
                    - "*"
                  exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
                  exclude_lines: ['^DBG']
                  exclude_lines: ['^DEBUG']
                  tail_files: true

    fields_under_root: true
    fields:
      hostname: ${NODE_NAME}


    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      #index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
      indices:
        - index: "docker-%{+yyyy.MM.dd}"
          when.equals:
            prospector.type: docker
