apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter-cluster
spec:
  template:
    metadata:
      labels:
        app: node-exporter-cluster
      name: node-exporter-cluster
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key": "node.alpha.kubernetes.io/ismaster", "effect": "NoSchedule"}]'
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter-cluster
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        volumeMounts:
        - name: data-disk
          mountPath: /data-disk
          readOnly: true
        - name: root-disk
          mountPath: /root-disk
          readOnly: true
      volumes:
        - name: data-disk
          hostPath:
            path: /datastore
        - name: root-disk
          hostPath:
            path: /
      hostNetwork: true
      hostPID: true