#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heikin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heikin
    spec:
      containers:
      - name: heikin
        image: egaraev/heikin:latest
        imagePullPolicy: Always
#        resources:
#          limits:
#            cpu: "1"
        volumeMounts:
        - name: tz-config
            mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Warsaw

