#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neuralanalyze
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neuralanalyze
    spec:
      volumes:
      - name: neural-nfs-pv
        persistentVolumeClaim:
          claimName: neural-nfs-claim0
      containers:
      - name: neuralanalyze
        image: egaraev/neuralanalyze:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.5"
            memory: 400Mi
        volumeMounts:
        - name: neural-nfs-pv
          mountPath: /usr/local/bin/data