#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tools
    spec:
      volumes:
      - name: tools-nfs-pv
        persistentVolumeClaim:
          claimName: tools-nfs-claim0
      containers:
      - name: tools
        image: egaraev/tools:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
        volumeMounts:
        - name: tools-nfs-pv
          mountPath: /usr/local/bin/data