#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: tools
        image: egaraev/tools:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.05"
            memory: 100Mi