kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  namespace: crypto
  name: nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/nfs
parameters:
  path: /exports/nfsshare
  server: 192.168.1.128