---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tools-nfs-pv
spec:
  claimRef:
    namespace: crypto
    name: tools-nfs-claim0
  storageClassName: nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.128
    path: "/exports/nfsshare/charts"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tools-nfs-claim0
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi