#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trading
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
      - name: trading
        image: egaraev/trading:latest
        imagePullPolicy: Always
#        resources:
#          limits:
#            cpu: "0.4"
#            memory: 400Mi
        volumeMounts:
        - name: tz-config
            mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Warsaw