apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - k8sworker.local
    secretName: testsecret-tls
  rules:
  - host: k8sworker.local
    http:
      paths:
        - path: /phpmyadmin/
          backend:
            serviceName: phpmyadmin
            servicePort: 80
#        - path: /webinterface/
#          backend:
#            serviceName: webinterface-service
#            servicePort: 8181
#  - host: phpmyadmin.k8sworker.local
#    http:
#        paths:
#        - backend:
#            serviceName: phpmyadmin
#            servicePort: 80