---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
#  type: NodePort
  ports:
    - port: 3306
      targetPort: 336
      name: sql
    - port: 22
      targetPort: 49160
      name: ssh
    - port: 8081
      targetPort: 49161
      name: webserver
  selector:
    app: database