#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
       app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: database-nfs-pv
        persistentVolumeClaim:
          claimName: database-nfs-claim0
      containers:
      - name: database
#        image: egaraev/mysql-eldar:demo
#        image: wnameless/mysql-phpmyadmin
        image: mysql/mysql-server:5.5.50
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
#        - name: MYSQL_DATABASE
#          value: 'cryptodb'
        imagePullPolicy: Always
        ports:
        - name: sql
          containerPort: 3306
#        resources:
#          limits:
#            cpu: "0.2"
#            memory: 200Mi
        volumeMounts:
        - name: database-nfs-pv
          mountPath: /var/lib/mysql